# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '4.0-To-Do' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Bond'
pod 'RealmSwift'
  # Pods for 4.0-To-Do

end
